### ISSUE TITLE
why cpu time is zero

### ISSUE THREAD

**Issue by Joyboyzjc** [BigDataAnalyticsGroup/analysis-rmi#12]
when I print scripts/run_index_comparison.sh
it shows that it dosen't use cpu
as follows
![cpu时间为0](https://github.com/BigDataAnalyticsGroup/analysis-rmi/assets/128047377/095a6325-9acf-40c5-8126-521fcea4b42d)

**Comment by marcelmaltry** [comment]
Thank you for reaching out! To better assist you, I need a bit more information:

- Did the project build successfully?
- What is the output of the script?
- Which environment or platform are you using?

With this additional information, I'll be better equipped to help you troubleshoot the problem.

**Comment by marcelmaltry** [comment]
I think this is fine. The bash script will execute the `index_comparison` binary, e.g.
`build/bin/index_comparison --n_reps 3 --n_samples 20000000 --rmi --alex --pgm --rs --tlx --ref --bin data/wiki_ts_200M_uint64`.
This will use CPU.

**Comment by Joyboyzjc** [comment]
Thank you very much for your help. As you said, there is really no problem. It is me. Thank you very much

**Comment by marcelmaltry** [comment]
Glad to be of help. I'll close the issue then.
